#!/usr/bin/env python3
"""Generate the English HMS lookup table offline using Python's standard library.

The JSON contains the complete pinned code mapping and the official English
source text for each concise display message. No network access is required.
Run with --check to verify that the committed header matches the JSON.
"""

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
LEVELS = {"info": 0, "warning": 1, "critical": 2}
CODE_FIELDS = ["attr", "code", "message", "category", "level", "unit", "ht", "slot"]


def display_text(value, limit, label):
    if not isinstance(value, str) or not 1 <= len(value) <= limit:
        raise ValueError(f"{label}: expected 1..{limit} characters")
    if any(ord(char) < 32 or ord(char) > 126 for char in value):
        raise ValueError(f"{label}: display text must contain printable ASCII")
    return json.dumps(value, ensure_ascii=True)


def code_number(value):
    if not isinstance(value, str) or len(value) != 10 or not value.startswith("0x"):
        raise ValueError("HMS code must use 0x followed by eight hexadecimal digits")
    number = int(value, 16)
    if not 0 <= number <= 0xFFFFFFFF:
        raise ValueError("HMS code is outside the uint32 range")
    return number


def integer(value, minimum, maximum, label):
    if type(value) is not int or not minimum <= value <= maximum:
        raise ValueError(f"{label}: expected integer {minimum}..{maximum}")
    return value


def generate(data):
    if data.get("schema") != 1 or data.get("code_fields") != CODE_FIELDS:
        raise ValueError("Unsupported HMS JSON schema")
    version = data["source"]["version"]
    if not isinstance(version, str) or not version.isascii() or not version.isdigit():
        raise ValueError("Source version must contain ASCII digits")
    categories = data["categories"]
    messages = data["messages"]
    codes = data["codes"]
    if not 1 <= len(categories) <= 256 or not 1 <= len(messages) <= 65536 or not codes:
        raise ValueError("Empty or oversized HMS table")
    lines = [
        "// Generated by firmware/hms/generate.py from firmware/hms/hms_en.json.",
        f"// Bambu Lab official HMS catalogue version {version}. Do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "struct HmsCodigo { uint32_t a, c; uint16_t txt; uint8_t cat, nivel; char unid; uint8_t ht, slot; };",
        "static const char* const HMS_CAT[] = {",
    ]
    lines += [f"  {display_text(category, 23, 'category')}," for category in categories]
    lines += ["};", "static const char* const HMS_TXT[] = {"]
    for index, message in enumerate(messages):
        if not isinstance(message.get("en"), list) or not message["en"]:
            raise ValueError(f"message {index}: official English source text missing")
        if any(not isinstance(source, str) or not source for source in message["en"]):
            raise ValueError(f"message {index}: invalid official English source text")
        lines.append(f"  {display_text(message['text'], 50, f'message {index}')},")
    lines += ["};", "static const HmsCodigo HMS_COD[] = {"]
    previous = None
    for row in codes:
        if not isinstance(row, list) or len(row) != len(CODE_FIELDS):
            raise ValueError("Invalid HMS code row")
        attr, code, message, category, level, unit, ht, slot = row
        pair = code_number(attr), code_number(code)
        if previous is not None and pair <= previous:
            raise ValueError("HMS codes must be unique and sorted by attr, code")
        previous = pair
        integer(message, 0, len(messages) - 1, "message index")
        integer(category, 0, len(categories) - 1, "category index")
        integer(slot, 0, 255, "slot")
        if level not in LEVELS:
            raise ValueError("Unknown HMS severity")
        if unit not in ("", "A", "B", "C", "D", "E", "F", "G", "H") or type(ht) is not bool:
            raise ValueError("Invalid AMS unit or HT flag")
        unit_literal = f"'{unit}'" if unit else "0"
        lines.append(
            f"  {{0x{pair[0]:08X}, 0x{pair[1]:08X}, {message}, {category}, "
            f"{LEVELS[level]}, {unit_literal}, {int(ht)}, {slot}}},"
        )
    lines += [
        "};",
        "static const int HMS_N = sizeof HMS_COD / sizeof HMS_COD[0];",
        "",
        "// Binary search for the attr/code pair reported by the printer.",
        "inline const HmsCodigo* hmsBusca(uint32_t a, uint32_t c) {",
        "  int lo = 0, hi = HMS_N - 1;",
        "  while (lo <= hi) {",
        "    int m = (lo + hi) / 2; const HmsCodigo& e = HMS_COD[m];",
        "    if (e.a == a && e.c == c) return &e;",
        "    if (e.a < a || (e.a == a && e.c < c)) lo = m + 1; else hi = m - 1;",
        "  }",
        "  return nullptr;",
        "}",
        "",
    ]
    return "\n".join(lines).encode("ascii")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=HERE / "hms_en.json")
    parser.add_argument("--output", type=Path, default=HERE.parent / "claudinho" / "hms_en.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        data = json.loads(args.input.read_text(encoding="utf-8"))
        header = generate(data)
        if args.check:
            if not args.output.exists() or args.output.read_bytes() != header:
                parser.exit(1, "HMS header differs from JSON; run generate.py.\n")
        else:
            args.output.write_bytes(header)
    except (OSError, ValueError, KeyError, TypeError) as error:
        parser.exit(1, f"HMS generation failed: {error}\n")
    print(f"{args.output.name}: {len(data['codes'])} codes, {len(data['messages'])} messages, {len(data['categories'])} categories")


if __name__ == "__main__":
    main()
